# Generated by Django 4.1.2 on 2022-10-26 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('GASTO', models.CharField(max_length=100)),
                ('COMENTARIO', models.TextField(blank=True)),
                ('IMPORTANTE', models.BooleanField(default=False)),
                ('VALOR', models.CharField(max_length=20)),
                ('FECHA_CREACION', models.DateTimeField(auto_now_add=True)),
                ('ESTADO', models.CharField(default=None, max_length=20)),
                ('TIPO_GASTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.par_tipo_gastos')),
                ('USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ganancias',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('GANANCIA', models.CharField(max_length=100)),
                ('COMENTARIO', models.TextField(blank=True)),
                ('IMPORTANTE', models.BooleanField(default=False)),
                ('VALOR', models.CharField(max_length=20)),
                ('FECHA_CREACION', models.DateTimeField(auto_now_add=True)),
                ('ESTADO', models.CharField(default=None, max_length=20)),
                ('TIPO_GANANCIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.par_tipo_gastos')),
                ('USUARIO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
