# Generated by Django 4.1.2 on 2022-10-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='par_tipo_ganancias',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=100)),
                ('COMENTARIO', models.CharField(max_length=100)),
                ('TIPO', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='par_tipo_gastos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRIPCION', models.CharField(max_length=100)),
                ('COMENTARIO', models.CharField(max_length=100)),
                ('TIPO', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
